### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [Richie765/pg-table-observer#1]
before you disconnect: https://github.com/Richie765/pg-table-observer/blob/master/src/PgTableObserver.js#L321

...best is to execute `UNLISTEN channel` first :wink:

**Comment by Richie765** [comment]
Done, thanks! :-)

**Comment by vitaly-t** [comment]
and with version 6.x of pg-promise you should no longer use [pgp.end()](http://vitaly-t.github.io/pg-promise/module-pg-promise.html#~end) they way you do. See the API from the link ;)

i.e. you should shut down only the pool you use ;)
